# Generated by ChatGPT on 2026-04-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_legacy_comments(apps, schema_editor):
    Comment = apps.get_model("posts", "Comment")
    PostComment = apps.get_model("posts", "PostComment")

    # If there is already data, don't duplicate.
    if PostComment.objects.exists():
        return

    batch = []
    for c in Comment.objects.all().order_by("id").iterator():
        batch.append(
            PostComment(
                content=(c.content or "")[:2000],
                created_at=c.created_at,
                author_id=c.author_id,
                post_id=c.post_id,
            )
        )
        if len(batch) >= 1000:
            PostComment.objects.bulk_create(batch, batch_size=1000)
            batch = []
    if batch:
        PostComment.objects.bulk_create(batch, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.CharField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comments",
                        to="posts.post",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="posts.postcomment",
                    ),
                ),
                (
                    "root",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="descendants",
                        to="posts.postcomment",
                    ),
                ),
            ],
            options={
                "db_table": "post_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(fields=["post", "created_at"], name="post_comment_post_created"),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(fields=["root", "created_at"], name="post_comment_root_created"),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(fields=["parent", "created_at"], name="post_comment_parent_created"),
        ),
        migrations.RunPython(copy_legacy_comments, reverse_code=migrations.RunPython.noop),
    ]

