# Generated by Django 6.0.3 on 2026-04-17 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_category_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '貼文', 'verbose_name_plural': '貼文'},
        ),
    ]
