# Generated by Django 5.2.5 on 2026-04-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_image2_post_image3_alter_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
