# Generated by Django 5.2.5 on 2026-04-20 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='', verbose_name='提問文字')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai_chat/', verbose_name='提問圖片')),
                ('assistant_reply', models.TextField(blank=True, default='', verbose_name='AI 回覆')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': 'AI 對話紀錄',
                'verbose_name_plural': 'AI 對話紀錄',
                'db_table': 'ai_chat_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
