# Generated by Django 5.2.5 on 2026-04-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_aichatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatlog',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='模型'),
        ),
    ]
