# Generated by Django 5.2.5 on 2026-04-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_aichatlog_model_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['created_at'], 'verbose_name': '貼文留言', 'verbose_name_plural': '貼文留言'},
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', '所有人'), ('private', '只有自己')], default='public', max_length=20, verbose_name='可見性'),
        ),
    ]
