"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    # utf-8-sig：避免 Windows 儲存 .env 時帶 BOM，導致讀不到 GEMINI_API_KEY
    load_dotenv(BASE_DIR / ".env", encoding="utf-8-sig")
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-dev-only-change-me").strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "false").strip().lower() in ("1", "true", "yes", "on")

ALLOWED_HOSTS = [h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    "accounts.apps.AccountsConfig",
    "posts.apps.PostsConfig",
    "import_export",
    "js_asset",
    "ckeditor",
    "ckeditor_uploader",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "captcha",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'mysite.context_processors.wheel_tags',
                'mysite.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Default: SQLite (no MariaDB required). For MariaDB, set env USE_MYSQL=1 and start the server.
# _USE_MYSQL = os.environ.get("USE_MYSQL", "").strip().lower() in ("1", "true", "yes")

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE", "django.db.backends.mysql").strip(),
        "NAME": os.environ.get("DB_NAME", "eat_what").strip(),
        "USER": os.environ.get("DB_USER", "").strip(),
        "PASSWORD": os.environ.get("DB_PASSWORD", "").strip(),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1").strip(),
        "PORT": os.environ.get("DB_PORT", "3308").strip(),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

LANGUAGES = [
    ('zh-hant', '繁體中文'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

USE_I18N = True

USE_TZ = True

# Logging（開發：console；正式：可改為檔案 handler）
_LOG_LEVEL = os.environ.get("LOG_LEVEL", "DEBUG" if DEBUG else "INFO").strip().upper()
_LOG_DIR = BASE_DIR / "logs"
_LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "ai_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": _LOG_DIR / "ai.log",
            "maxBytes": 2 * 1024 * 1024,
            "backupCount": 3,
            "encoding": "utf-8",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "posts.ai_chat": {
            "handlers": ["console", "ai_file"],
            "level": _LOG_LEVEL,
            "propagate": False,
        },
        "posts.views": {
            "handlers": ["console"],
            "level": _LOG_LEVEL,
            "propagate": False,
        },
        "posts.api": {
            "handlers": ["console", "ai_file"],
            "level": _LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "EXCEPTION_HANDLER": "posts.api.exceptions.api_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

if DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append(
        "rest_framework.renderers.BrowsableAPIRenderer"
    )

SPECTACULAR_SETTINGS = {
    "TITLE": "等等吃啥 API",
    "DESCRIPTION": "等等吃啥（EatWhat）後端 API 文件。目前提供 AI 美食助理等 DRF 端點。",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/v1",
    "TAGS": [
        {"name": "AI Chat", "description": "AI 美食助理對話 API"},
        {"name": "Posts", "description": "貼文 CRUD、按讚、收藏"},
        {"name": "Comments", "description": "留言 CRUD、按讚"},
        {"name": "Notifications", "description": "通知中心"},
        {"name": "Collections", "description": "我的收藏"},
        {"name": "Taxonomy", "description": "分類與標籤（管理員可寫入）"},
        {"name": "Users", "description": "使用者檔案、追蹤"},
    ],
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'
SITE_ID = int(os.environ.get("SITE_ID", "1").strip() or "1")

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'posts:feed'

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_EMAIL_VERIFICATION = os.environ.get("ACCOUNT_EMAIL_VERIFICATION", "none").strip()
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_UNIQUE_EMAIL = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_STORE_TOKENS = False
SOCIALACCOUNT_FORMS = {
    "signup": "accounts.forms.SocialSignupForm",
}
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", "").strip(),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", "").strip(),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

# django-simple-captcha（登入／註冊圖片驗證碼）
CAPTCHA_LENGTH = 5
CAPTCHA_TIMEOUT = 5
CAPTCHA_IMAGE_SIZE = (140, 48)
CAPTCHA_FONT_SIZE = 30
CAPTCHA_LETTER_ROTATION = (-25, 25)
CAPTCHA_BACKGROUND_COLOR = "#f4f7f8"
CAPTCHA_FOREGROUND_COLOR = "#0b2b30"

# Google Gemini（美食助理）：金鑰來源 https://aistudio.google.com/app/apikey
GEMINI_API_KEY = (
    os.environ.get("GEMINI_API_KEY", "").strip()
    # Back-compat：第三組 key 改名時也可沿用（例如 NVIDIA_BACKUP_API_KEY2）
    or os.environ.get("NVIDIA_BACKUP_API_KEY2", "").strip()
)
# 例如 gemini-2.0-flash、gemini-1.5-flash（需帳戶可用模型）
GEMINI_MODEL = (
    os.environ.get("GEMINI_MODEL", "").strip()
    or os.environ.get("NVIDIA_BACKUP_MODEL2", "").strip()
    or "gemini-2.0-flash"
)

# NVIDIA Integrate（OpenAI 風格 Chat Completions）
NVIDIA_API_KEY = (
    os.environ.get("NVIDIA_API_KEY", "").strip()
    # Back-compat：main.py / 教學常用 generic `api_key`
    or os.environ.get("api_key", "").strip()
)
NVIDIA_MODEL = os.environ.get("NVIDIA_MODEL", "qwen/qwen3.5-397b-a17b").strip()
NVIDIA_INVOKE_URL = os.environ.get(
    "NVIDIA_INVOKE_URL", "https://integrate.api.nvidia.com/v1/chat/completions"
).strip()
NVIDIA_BACKUP_API_KEY = os.environ.get("NVIDIA_BACKUP_API_KEY", "").strip()
NVIDIA_BACKUP_MODEL = os.environ.get("NVIDIA_BACKUP_MODEL", NVIDIA_MODEL).strip()
AI_REQUEST_TIMEOUT_SECONDS = int(os.environ.get("AI_REQUEST_TIMEOUT_SECONDS", "35").strip() or "35")

# Celery（背景任務：健康達人分析）
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0").strip()
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/1").strip()
CELERY_TASK_ALWAYS_EAGER = os.environ.get("CELERY_TASK_ALWAYS_EAGER", "0").strip().lower() in (
    "1",
    "true",
    "yes",
)

# CKEditor（富文字 + 圖片上傳）
CKEDITOR_UPLOAD_PATH = "ckeditor_uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
# True 時依使用者名稱分資料夾；若設為字串則為 User 的屬性名稱
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_CONFIGS = {
    "default": {
        # 使用 Full 工具列並補上字型／字級（套件預設 Full 沒有 Font／FontSize）
        "toolbar": "Full",
        "height": 380,
        "width": "100%",
        "toolbar_Full": [
            [
                "Styles",
                "Format",
                "Font",
                "FontSize",
                "Bold",
                "Italic",
                "Underline",
                "Strike",
                "Subscript",
                "Superscript",
            ],
            ["TextColor", "BGColor"],
            ["Link", "Unlink", "Image", "Table", "HorizontalRule"],
            [
                "JustifyLeft",
                "JustifyCenter",
                "JustifyRight",
                "JustifyBlock",
            ],
            [
                "NumberedList",
                "BulletedList",
                "Outdent",
                "Indent",
                "Blockquote",
            ],
            ["RemoveFormat", "Source"],
        ],
        # 字級選項（可依需求增減）
        "fontSize_sizes": (
            "12/12px;14/14px;16/16px;18/18px;20/20px;24/24px;28/28px;32/32px;36/36px"
        ),
        "fontSize_defaultLabel": "16",
    },
}

# bleach：儲存前允許的 HTML（與 CKEditor 輸出對齊）
BLEACH_ALLOWED_TAGS = [
    "p",
    "br",
    "strong",
    "b",
    "em",
    "i",
    "u",
    "s",
    "sub",
    "sup",
    "h1",
    "h2",
    "h3",
    "h4",
    "ul",
    "ol",
    "li",
    "a",
    "img",
    "blockquote",
    "div",
    "span",
    # CKEditor 舊版或部分設定仍可能輸出 <font>
    "font",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
    "hr",
]
BLEACH_ALLOWED_ATTRIBUTES = {
    "*": ["class", "style"],
    "a": ["href", "title", "rel", "target"],
    "img": ["src", "alt", "title", "width", "height", "style"],
    "font": ["color", "face", "size"],
}
BLEACH_ALLOWED_PROTOCOLS = ["http", "https", "data", "mailto"]
