"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    # utf-8-sig：避免 Windows 儲存 .env 時帶 BOM，導致讀不到 GEMINI_API_KEY
    load_dotenv(BASE_DIR / ".env", encoding="utf-8-sig")
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y4i_3xy6scex!lpnodg*4h5ot=eg+m-%rc9c47)!&j%cv^7-zu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "accounts.apps.AccountsConfig",
    "posts.apps.PostsConfig",
    "import_export",
    "js_asset",
    "ckeditor",
    "ckeditor_uploader",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Default: SQLite (no MariaDB required). For MariaDB, set env USE_MYSQL=1 and start the server.
# _USE_MYSQL = os.environ.get("USE_MYSQL", "").strip().lower() in ("1", "true", "yes")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "eat_what",
        "USER": "root",
        "PASSWORD": "1234",
        "HOST": "127.0.0.1",
        "PORT": "3307",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

LANGUAGES = [
    ('zh-hant', '繁體中文'),
]

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'posts:feed'

# Google Gemini（美食助理）：金鑰來源 https://aistudio.google.com/app/apikey
GEMINI_API_KEY = (
    os.environ.get("NVIDIA_API_KEY", "").strip()
    or os.environ.get("api_key", "").strip()
)
# 例如 gemini-2.0-flash、gemini-1.5-flash（需帳戶可用模型）
GEMINI_MODEL = os.environ.get("NVIDIA_MODEL", "nvidia/nemotron-3-nano-30b-a3b")

# NVIDIA Integrate（OpenAI 風格 Chat Completions）
NVIDIA_API_KEY = (
    os.environ.get("NVIDIA_API_KEY", "").strip()
    # Back-compat：main.py / 教學常用 generic `api_key`
    or os.environ.get("api_key", "").strip()
)
NVIDIA_MODEL = os.environ.get("NVIDIA_MODEL", "qwen/qwen3.5-397b-a17b").strip()
NVIDIA_INVOKE_URL = os.environ.get(
    "NVIDIA_INVOKE_URL", "https://integrate.api.nvidia.com/v1/chat/completions"
).strip()

# CKEditor（富文字 + 圖片上傳）
CKEDITOR_UPLOAD_PATH = "ckeditor_uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
# True 時依使用者名稱分資料夾；若設為字串則為 User 的屬性名稱
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_CONFIGS = {
    "default": {
        # 使用 Full 工具列並補上字型／字級（套件預設 Full 沒有 Font／FontSize）
        "toolbar": "Full",
        "height": 380,
        "width": "100%",
        "toolbar_Full": [
            [
                "Styles",
                "Format",
                "Font",
                "FontSize",
                "Bold",
                "Italic",
                "Underline",
                "Strike",
                "Subscript",
                "Superscript",
            ],
            ["TextColor", "BGColor"],
            ["Link", "Unlink", "Image", "Table", "HorizontalRule"],
            [
                "JustifyLeft",
                "JustifyCenter",
                "JustifyRight",
                "JustifyBlock",
            ],
            [
                "NumberedList",
                "BulletedList",
                "Outdent",
                "Indent",
                "Blockquote",
            ],
            ["RemoveFormat", "Source"],
        ],
        # 字級選項（可依需求增減）
        "fontSize_sizes": (
            "12/12px;14/14px;16/16px;18/18px;20/20px;24/24px;28/28px;32/32px;36/36px"
        ),
        "fontSize_defaultLabel": "16",
    },
}

# bleach：儲存前允許的 HTML（與 CKEditor 輸出對齊）
BLEACH_ALLOWED_TAGS = [
    "p",
    "br",
    "strong",
    "b",
    "em",
    "i",
    "u",
    "s",
    "sub",
    "sup",
    "h1",
    "h2",
    "h3",
    "h4",
    "ul",
    "ol",
    "li",
    "a",
    "img",
    "blockquote",
    "div",
    "span",
    # CKEditor 舊版或部分設定仍可能輸出 <font>
    "font",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
    "hr",
]
BLEACH_ALLOWED_ATTRIBUTES = {
    "*": ["class", "style"],
    "a": ["href", "title", "rel", "target"],
    "img": ["src", "alt", "title", "width", "height", "style"],
    "font": ["color", "face", "size"],
}
BLEACH_ALLOWED_PROTOCOLS = ["http", "https", "data", "mailto"]
